export default {
  FETCH_POSTS: 'FETCH_POSTS',
  FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
  FETCH_POSTS_ERROR: 'FETCH_POSTS_ERROR',
  DISMISS_POST: 'DISMISS_POST',
  DISMISS_ALL: 'DISMISS_ALL',
  SELECT_POST: 'SELECT_POST'
};